-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 19:03:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `KLIENT`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `KLIENT` (
  `id_klienta` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `datum_narozeni` DATE NOT NULL, CHECK (`datum_narozeni` < '2023-01-01'),
  `telefon` VARCHAR(15) NOT NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id_klienta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SLUZBA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SLUZBA` ;

CREATE TABLE IF NOT EXISTS `SLUZBA` (
  `id_sluzby` INT NOT NULL AUTO_INCREMENT,
  `typ` VARCHAR(45) NOT NULL,
  `cena` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id_sluzby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ADVOKAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ADVOKAT` ;

CREATE TABLE IF NOT EXISTS `ADVOKAT` (
  `id_advokata` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `titul` VARCHAR(45) NOT NULL,
  `pocatek_praxe` DATE NOT NULL CHECK (`pocatek_praxe` BETWEEN  '1920-01-01' AND '2023-01-01'),
  `specializace` VARCHAR(45) NULL,
  PRIMARY KEY (`id_advokata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SMLOUVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SMLOUVA` ;

CREATE TABLE IF NOT EXISTS `SMLOUVA` (
  `cislo_smlouvy` INT NOT NULL AUTO_INCREMENT,
  `typ` VARCHAR(45) NOT NULL,
  `id_advokata` INT NOT NULL,
  `id_klienta` INT NOT NULL,
  `id_sluzby` INT NOT NULL,
   `datum_uzavreni` DATE NOT NULL,
  PRIMARY KEY (`cislo_smlouvy`),
  INDEX `fk_Smlouva_KLIENT1_idx` (`id_klienta`ASC),
  INDEX `fk_Smlouva_ADVOKÁT1_idx` (`id_advokata`ASC),
  INDEX `fk_SMLOUVA_SLUZBA1_idx` (`id_sluzby` ASC),
  CONSTRAINT `fk_Smlouva_KLIENT1`
    FOREIGN KEY (`id_klienta`)
    REFERENCES `KLIENT` (`id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Smlouva_ADVOKÁT1`
    FOREIGN KEY (`id_advokata`)
    REFERENCES `ADVOKAT` (`id_advokata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SMLOUVA_SLUZBA1`
    FOREIGN KEY (`id_sluzby`)
    REFERENCES `SLUZBA` (`id_sluzby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `poskytuje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poskytuje` ;

CREATE TABLE IF NOT EXISTS `poskytuje` (
  `id_advokata` INT NOT NULL,
  `id_sluzby` INT NOT NULL,
  INDEX `fk_ADVOKÁT_has_SLUŽBA_SLUŽBA1_idx` (`id_sluzby` ASC),
  INDEX `fk_ADVOKÁT_has_SLUŽBA_ADVOKÁT1_idx` (`id_advokata` ASC),
  PRIMARY KEY (`id_advokata`, `id_sluzby`),
  CONSTRAINT `fk_ADVOKÁT_has_SLUŽBA_ADVOKÁT1`
    FOREIGN KEY (`id_advokata`)
    REFERENCES `ADVOKAT` (`id_advokata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADVOKÁT_has_SLUŽBA_SLUŽBA1`
    FOREIGN KEY (`id_sluzby`)
    REFERENCES `SLUZBA` (`id_sluzby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ADVOKATNI SPIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ADVOKATNI SPIS` ;

CREATE TABLE IF NOT EXISTS `ADVOKATNI SPIS` (
  `cislo_spisu` INT NOT NULL AUTO_INCREMENT,
  `id_advokata` INT NOT NULL,
  `cislo_smlouvy` INT NOT NULL,
	`dotcene_organy` VARCHAR(300) NULL,
  `lhuty` VARCHAR(150) NULL,
  `ukony` VARCHAR(200) NULL,
  `poznamky` VARCHAR(1000) NULL,
  `pocatek_vedeni_spisu` DATE NOT NULL,
  `konec_vedeni_spisu` DATE NULL,
  PRIMARY KEY (`cislo_spisu`),
  INDEX `fk_ADVOKÁTNÍ SPIS_ADVOKÁT1_idx` (`id_advokata` ASC),
  INDEX `fk_ADVOKATNI SPIS_SMLOUVA1_idx` (`cislo_smlouvy` ASC),
  CONSTRAINT `fk_ADVOKÁTNÍ SPIS_ADVOKÁT1`
    FOREIGN KEY (`id_advokata`)
    REFERENCES `ADVOKAT` (`id_advokata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADVOKATNI SPIS_SMLOUVA1`
    FOREIGN KEY (`cislo_smlouvy`)
    REFERENCES `SMLOUVA` (`cislo_smlouvy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `ADVOKAT` ADD CHECK ('1920-01-01'< `pocatek_praxe` < '2023-01-01');
ALTER TABLE `KLIENT` ADD CHECK (`datum_narozeni`< '2023-01-01');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
